export type PrimaryMenuCategory =
  | "Drinks"
  | "Breakfast"
  | "Snacks"
  | "Veg"
  | "Non-Veg"
  | "Chinese"
  | "Tandoori"
  | "Main Course"
  | "Raita"
  | "Important";

export type DietType = "veg" | "non-veg" | "egg" | "both" | "drink";

export interface DigitalMenuItem {
  id: string;
  name: string;
  price: string;
  priceHalf?: string;
  priceFull?: string;
  priceVeg?: string;
  priceNonVeg?: string;
  priceType: "single" | "portion" | "diet_dual";
  description?: string;
  primaryCategory:
    | "Drinks"
    | "Breakfast"
    | "Snacks"
    | "Chinese"
    | "Tandoori"
    | "Main Course"
    | "Raita";
  subcategory: string;
  diet: DietType;
  isSpecial?: boolean;
}

export const MENU_CATEGORIES = [
  "All",
  "Drinks",
  "Breakfast",
  "Snacks",
  "Veg",
  "Non-Veg",
  "Chinese",
  "Tandoori",
  "Main Course",
  "Raita",
  "Important",
] as const;

export type MenuCategoryTab = (typeof MENU_CATEGORIES)[number];

export const IMPORTANT_NOTES = [
  "Drinking Beer from outside is strictly prohibited.",
  "Beer has 14.5 VAT extra.",
  "In case of vomiting a fine of Rs. 300 will be charged.",
  "You will get the order within 20 minutes of placing the order.",
  "CGST 2.5% extra & SGST 2.5% extra.",
  "Last order will be taken by 10:30 PM.",
] as const;

export const digitalMenuItems: DigitalMenuItem[] = [
  // ==========================================
  // DRINKS: MOCKTAILS
  // ==========================================
  {
    id: "virgin-mojito",
    name: "Virgin Mojito",
    price: "₹150",
    priceType: "single",
    description: "Lemon Chunks, Mint Leaves, Crushed Ice, Sugar Syrup, Topped with Soda & Sprite",
    primaryCategory: "Drinks",
    subcategory: "Mocktails",
    diet: "drink",
  },
  {
    id: "virgin-mary",
    name: "Virgin Mary",
    price: "₹140",
    priceType: "single",
    description: "Tomato Juice, Lemon Juice, Tabasco & Worcestershire Sauce, Salt, Pepper",
    primaryCategory: "Drinks",
    subcategory: "Mocktails",
    diet: "drink",
  },
  {
    id: "blue-lagoon-mocktail",
    name: "Blue Lagoon",
    price: "₹150",
    priceType: "single",
    description: "Lemon Juice, Blue Curacao, Sugar Syrup, Soda & Sprite",
    primaryCategory: "Drinks",
    subcategory: "Mocktails",
    diet: "drink",
  },
  {
    id: "passion-on-fire",
    name: "Passion On Fire",
    price: "₹150",
    priceType: "single",
    description: "Lemon Juice, Pineapple Juice Topped with Soda",
    primaryCategory: "Drinks",
    subcategory: "Mocktails",
    diet: "drink",
  },
  {
    id: "shah-junction-punch",
    name: "Shah Junction Punch",
    price: "₹170",
    priceType: "single",
    description: "Guava Juice, Vanilla Ice Cream, Shaked Well & Served in Rum Glass",
    primaryCategory: "Drinks",
    subcategory: "Mocktails",
    diet: "drink",
    isSpecial: true,
  },
  {
    id: "black-mojito",
    name: "Black Mojito",
    price: "₹150",
    priceType: "single",
    description: "Crushed Ice, Lemon Chunks, Mint Leaves, Sugar Syrup, Topped with Coke",
    primaryCategory: "Drinks",
    subcategory: "Mocktails",
    diet: "drink",
  },
  {
    id: "pineapple-cobbler",
    name: "Pineapple Cobbler",
    price: "₹150",
    priceType: "single",
    description: "Strawberry Juice, Lime Juice, Pineapple Juice, Topped with Soda",
    primaryCategory: "Drinks",
    subcategory: "Mocktails",
    diet: "drink",
  },
  {
    id: "shah-junction-special-mocktail",
    name: "Shah Junction Special",
    price: "₹175",
    priceType: "single",
    description: "Guava Juice, Ice Cubes, Black Salt, Tabasco Sauce, Lemon Juice, Black Pepper, Shaked Well & Served in Salted Rum Glass",
    primaryCategory: "Drinks",
    subcategory: "Mocktails",
    diet: "drink",
    isSpecial: true,
  },
  {
    id: "ex-on-the-beach",
    name: "Ex-On The Beach",
    price: "₹150",
    priceType: "single",
    description: "Peach Syrup, Ice Cubes, Orange Juice, Cranberry Juice, Lemon Juice",
    primaryCategory: "Drinks",
    subcategory: "Mocktails",
    diet: "drink",
  },

  // ==========================================
  // DRINKS: BEVERAGES
  // ==========================================
  {
    id: "tea",
    name: "Tea",
    price: "₹40",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Beverages",
    diet: "drink",
  },
  {
    id: "hot-coffee",
    name: "Hot Coffee",
    price: "₹50",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Beverages",
    diet: "drink",
  },
  {
    id: "hot-chocolate",
    name: "Hot Chocolate",
    price: "₹80",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Beverages",
    diet: "drink",
  },
  {
    id: "bournvita-hot-milk",
    name: "Bournvita Hot Milk",
    price: "₹80",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Beverages",
    diet: "drink",
  },
  {
    id: "corn-flakes-with-milk",
    name: "Corn Flakes with Milk",
    price: "₹50",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Beverages",
    diet: "drink",
  },
  {
    id: "espresso-coffee",
    name: "Espresso Coffee",
    price: "₹40",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Beverages",
    diet: "drink",
  },
  {
    id: "lemon-tea",
    name: "Lemon Tea",
    price: "₹40",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Beverages",
    diet: "drink",
  },
  {
    id: "green-tea",
    name: "Green Tea",
    price: "₹40",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Beverages",
    diet: "drink",
  },
  {
    id: "fruit-punch",
    name: "Fruit Punch",
    price: "₹100",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Beverages",
    diet: "drink",
  },
  {
    id: "blue-lagoon-bev",
    name: "Blue Lagoon",
    price: "₹100",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Beverages",
    diet: "drink",
  },
  {
    id: "ice-cube",
    name: "Ice Cube",
    price: "₹40",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Beverages",
    diet: "drink",
  },

  // ==========================================
  // DRINKS: SHAKES & COLD DRINKS
  // ==========================================
  {
    id: "mineral-water",
    name: "Mineral Water",
    price: "₹30",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Shakes & Cold Drinks",
    diet: "drink",
  },
  {
    id: "soft-drinks-300ml",
    name: "300ml Soft Drinks",
    price: "₹30",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Shakes & Cold Drinks",
    diet: "drink",
  },
  {
    id: "soda-600ml",
    name: "Soda 600ml",
    price: "₹30",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Shakes & Cold Drinks",
    diet: "drink",
  },
  {
    id: "shake-any-flavor",
    name: "Shake Any Flavor",
    price: "₹140",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Shakes & Cold Drinks",
    diet: "drink",
  },
  {
    id: "cold-coffee",
    name: "Cold Coffee",
    price: "₹120",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Shakes & Cold Drinks",
    diet: "drink",
  },
  {
    id: "cold-coffee-with-ice-cream",
    name: "Cold Coffee with Ice-Cream",
    price: "₹160",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Shakes & Cold Drinks",
    diet: "drink",
  },
  {
    id: "juice-any-flavor",
    name: "Juice Any Flavor",
    price: "₹100",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Shakes & Cold Drinks",
    diet: "drink",
  },
  {
    id: "fresh-lime-water",
    name: "Fresh Lime Water",
    price: "₹60",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Shakes & Cold Drinks",
    diet: "drink",
  },
  {
    id: "fresh-lime-soda-sweet-salt",
    name: "Fresh Lime Soda Sweet/Salt",
    price: "₹80",
    priceType: "single",
    primaryCategory: "Drinks",
    subcategory: "Shakes & Cold Drinks",
    diet: "drink",
  },

  // ==========================================
  // BREAKFAST: PARATHAS
  // ==========================================
  {
    id: "aloo-paratha-with-curd",
    name: "Aloo Paratha with Curd",
    price: "₹100",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Parathas with Curd",
    diet: "veg",
  },
  {
    id: "gobhi-paratha-with-curd",
    name: "Gobhi Paratha with Curd",
    price: "₹100",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Parathas with Curd",
    diet: "veg",
  },
  {
    id: "muli-paratha-with-curd",
    name: "Muli Paratha with Curd",
    price: "₹100",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Parathas with Curd",
    diet: "veg",
  },
  {
    id: "mix-paratha-with-curd",
    name: "Mix Paratha with Curd",
    price: "₹100",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Parathas with Curd",
    diet: "veg",
  },

  // ==========================================
  // BREAKFAST / EGG & CHICKEN SANDWICH
  // ==========================================
  {
    id: "omelet-bhurji",
    name: "Omelet Bhurji",
    price: "₹80",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Egg & Chicken Sandwich",
    diet: "egg",
  },
  {
    id: "egg-sandwich",
    name: "Egg Sandwich",
    price: "₹100",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Egg & Chicken Sandwich",
    diet: "egg",
  },
  {
    id: "half-fry-egg",
    name: "Half Fry Egg",
    price: "₹70",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Egg & Chicken Sandwich",
    diet: "egg",
  },
  {
    id: "masala-omelet",
    name: "Masala Omelet",
    price: "₹100",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Egg & Chicken Sandwich",
    diet: "egg",
  },
  {
    id: "chicken-omelet",
    name: "Chicken Omelet",
    price: "₹130",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Egg & Chicken Sandwich",
    diet: "non-veg",
  },
  {
    id: "chicken-sandwich",
    name: "Chicken Sandwich",
    price: "₹150",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Egg & Chicken Sandwich",
    diet: "non-veg",
  },
  {
    id: "chicken-club-sandwich",
    name: "Chicken Club Sandwich",
    price: "₹170",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Egg & Chicken Sandwich",
    diet: "non-veg",
  },
  {
    id: "chicken-grilled-sandwich",
    name: "Chicken Grilled Sandwich",
    price: "₹250",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Egg & Chicken Sandwich",
    diet: "non-veg",
  },

  // ==========================================
  // BREAKFAST / VEG SANDWICH
  // ==========================================
  {
    id: "veg-sandwich",
    name: "Veg. Sandwich",
    price: "₹100",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Veg Sandwich",
    diet: "veg",
  },
  {
    id: "veg-club-sandwich",
    name: "Veg. Club Sandwich",
    price: "₹150",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Veg Sandwich",
    diet: "veg",
  },
  {
    id: "veg-grilled-sandwich",
    name: "Veg. Grilled Sandwich",
    price: "₹180",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Veg Sandwich",
    diet: "veg",
  },
  {
    id: "cheese-grilled-sandwich",
    name: "Cheese Grilled Sandwich",
    price: "₹220",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Veg Sandwich",
    diet: "veg",
  },
  {
    id: "cheese-sandwich",
    name: "Cheese Sandwich",
    price: "₹190",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Veg Sandwich",
    diet: "veg",
  },

  // ==========================================
  // BREAKFAST / TOAST & EGG
  // ==========================================
  {
    id: "butter-toast",
    name: "Butter Toast",
    price: "₹80",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Toast & Egg",
    diet: "veg",
  },
  {
    id: "butter-slice",
    name: "Butter Slice",
    price: "₹80",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Toast & Egg",
    diet: "veg",
  },
  {
    id: "butter-jam-toast",
    name: "Butter Jam Toast",
    price: "₹90",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Toast & Egg",
    diet: "veg",
  },
  {
    id: "boiled-egg-per-pc",
    name: "Boiled Egg Per Pc.",
    price: "₹40",
    priceType: "single",
    primaryCategory: "Breakfast",
    subcategory: "Toast & Egg",
    diet: "egg",
  },

  // ==========================================
  // SNACKS: SOUPS
  // ==========================================
  {
    id: "cream-of-tomato-soup",
    name: "Cream of Tomato Soup",
    price: "₹120",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Soups",
    diet: "veg",
  },
  {
    id: "hot-sour-soup",
    name: "Hot & Sour Soup",
    price: "₹120 / ₹160",
    priceVeg: "₹120",
    priceNonVeg: "₹160",
    priceType: "diet_dual",
    primaryCategory: "Snacks",
    subcategory: "Soups",
    diet: "both",
  },
  {
    id: "manchow-soup",
    name: "Manchow Soup",
    price: "₹120 / ₹160",
    priceVeg: "₹120",
    priceNonVeg: "₹160",
    priceType: "diet_dual",
    primaryCategory: "Snacks",
    subcategory: "Soups",
    diet: "both",
  },
  {
    id: "talumin-soup",
    name: "Talumin Soup",
    price: "₹120 / ₹160",
    priceVeg: "₹120",
    priceNonVeg: "₹160",
    priceType: "diet_dual",
    primaryCategory: "Snacks",
    subcategory: "Soups",
    diet: "both",
  },
  {
    id: "pasta-soup",
    name: "Pasta Soup",
    price: "₹120 / ₹160",
    priceVeg: "₹120",
    priceNonVeg: "₹160",
    priceType: "diet_dual",
    primaryCategory: "Snacks",
    subcategory: "Soups",
    diet: "both",
  },
  {
    id: "lemon-corriander-soup",
    name: "Lemon Corriander Soup",
    price: "₹120 / ₹160",
    priceVeg: "₹120",
    priceNonVeg: "₹160",
    priceType: "diet_dual",
    primaryCategory: "Snacks",
    subcategory: "Soups",
    diet: "both",
  },
  {
    id: "cream-of-chicken-soup",
    name: "Cream of Chicken Soup",
    price: "₹120 / ₹160",
    priceVeg: "₹120",
    priceNonVeg: "₹160",
    priceType: "diet_dual",
    primaryCategory: "Snacks",
    subcategory: "Soups",
    diet: "both",
  },
  {
    id: "cream-of-mushroom-soup",
    name: "Cream of Mushroom Soup",
    price: "₹120 / ₹160",
    priceVeg: "₹120",
    priceNonVeg: "₹160",
    priceType: "diet_dual",
    primaryCategory: "Snacks",
    subcategory: "Soups",
    diet: "both",
  },
  {
    id: "french-onion-soup",
    name: "French Onion Soup",
    price: "₹120 / ₹160",
    priceVeg: "₹120",
    priceNonVeg: "₹160",
    priceType: "diet_dual",
    primaryCategory: "Snacks",
    subcategory: "Soups",
    diet: "both",
  },
  {
    id: "tomato-shroba",
    name: "Tomato Shroba",
    price: "₹120",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Soups",
    diet: "veg",
  },

  // ==========================================
  // SNACKS: CONTINENTAL SIZZLERS
  // ==========================================
  {
    id: "veg-sizzler",
    name: "Veg Sizzler",
    price: "₹450",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Sizzlers",
    diet: "veg",
  },
  {
    id: "chicken-sizzler",
    name: "Chicken Sizzler",
    price: "₹550",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Sizzlers",
    diet: "non-veg",
  },
  {
    id: "cheese-grilled-sizzler",
    name: "Cheese Grilled Sizzler",
    price: "₹550",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Sizzlers",
    diet: "veg",
  },
  {
    id: "cheese-sizzler",
    name: "Cheese Sizzler",
    price: "₹500",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Sizzlers",
    diet: "veg",
  },
  {
    id: "spl-maxican-sizzlers",
    name: "Spl. Maxican Sizzlers",
    price: "₹500 / ₹600",
    priceVeg: "₹500",
    priceNonVeg: "₹600",
    priceType: "diet_dual",
    primaryCategory: "Snacks",
    subcategory: "Continental Sizzlers",
    diet: "both",
  },

  // ==========================================
  // SNACKS: CONTINENTAL VEG & NON-VEG
  // ==========================================
  {
    id: "fried-chicken",
    name: "Fried Chicken",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Snacks",
    subcategory: "Continental Veg & Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-pakoda",
    name: "Chicken Pakoda",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Snacks",
    subcategory: "Continental Veg & Non-Veg",
    diet: "non-veg",
  },
  {
    id: "boiled-veg-in-butter",
    name: "Boiled Veg. in Butter",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Veg & Non-Veg",
    diet: "veg",
  },
  {
    id: "paneer-stuff-pakoda",
    name: "Paneer Stuff Pakoda",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Veg & Non-Veg",
    diet: "veg",
  },
  {
    id: "cheese-finger",
    name: "Cheese Finger",
    price: "₹280",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Veg & Non-Veg",
    diet: "veg",
  },
  {
    id: "veg-cutlet",
    name: "Veg. Cutlet",
    price: "₹280",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Veg & Non-Veg",
    diet: "veg",
  },
  {
    id: "italian-finger",
    name: "Italian Finger",
    price: "₹230",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Veg & Non-Veg",
    diet: "veg",
  },
  {
    id: "veg-cocktail-kabab",
    name: "Veg. Cocktail Kabab",
    price: "₹250",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Veg & Non-Veg",
    diet: "veg",
  },
  {
    id: "french-fries",
    name: "French Fries",
    price: "₹140",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Veg & Non-Veg",
    diet: "veg",
  },
  {
    id: "veg-pakoda",
    name: "Veg. Pakoda",
    price: "₹190",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Veg & Non-Veg",
    diet: "veg",
  },
  {
    id: "paneer-pakoda",
    name: "Paneer Pakoda",
    price: "₹280",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Veg & Non-Veg",
    diet: "veg",
  },
  {
    id: "veg-harra-bhara-kabab",
    name: "Veg. Harra Bhara Kabab",
    price: "₹230",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Veg & Non-Veg",
    diet: "veg",
  },
  {
    id: "mushroom-duplex",
    name: "Mushroom Duplex",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Veg & Non-Veg",
    diet: "veg",
  },
  {
    id: "veg-pasta-red-white",
    name: "Veg. Pasta Red/White",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Veg & Non-Veg",
    diet: "veg",
  },
  {
    id: "chicken-pasta-red-white",
    name: "Chicken Pasta Red/White",
    price: "₹400",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Veg & Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-nagtis",
    name: "Chicken Nagtis",
    price: "₹400",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Continental Veg & Non-Veg",
    diet: "non-veg",
  },

  // ==========================================
  // SNACKS: VEG BURGER
  // ==========================================
  {
    id: "mix-veg-burger",
    name: "Mix Veg. Burger",
    price: "₹100",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Veg Burger",
    diet: "veg",
  },
  {
    id: "cream-salad-burger",
    name: "Cream Salad Burger",
    price: "₹120",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Veg Burger",
    diet: "veg",
  },
  {
    id: "paneer-burger",
    name: "Paneer Burger",
    price: "₹130",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Veg Burger",
    diet: "veg",
  },
  {
    id: "mushroom-burger",
    name: "Mushroom Burger",
    price: "₹100",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Veg Burger",
    diet: "veg",
  },
  {
    id: "maha-veg-burger",
    name: "Maha Veg. Burger",
    price: "₹140",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Veg Burger",
    diet: "veg",
  },
  {
    id: "shah-junction-special-burger",
    name: "Shah Junction Special Burger",
    price: "₹150",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Veg Burger",
    diet: "veg",
    isSpecial: true,
  },

  // ==========================================
  // SNACKS: VEG PIZZA
  // ==========================================
  {
    id: "shah-junction-special-pizza-veg",
    name: "Shah Junction Special Pizza",
    price: "₹350",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Veg Pizza",
    diet: "veg",
    isSpecial: true,
  },
  {
    id: "special-paneer-pizza",
    name: "Special Paneer Pizza",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Veg Pizza",
    diet: "veg",
  },
  {
    id: "veg-delight-pizza",
    name: "Veg. Delight Pizza",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Veg Pizza",
    diet: "veg",
  },
  {
    id: "mix-vegetarian-pizza",
    name: "Mix Vegetarian Pizza",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Veg Pizza",
    diet: "veg",
  },
  {
    id: "onion-mushroom-pizza",
    name: "Onion Mushroom Pizza",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Veg Pizza",
    diet: "veg",
  },
  {
    id: "onion-capsicum-pizza",
    name: "Onion Capsicum Pizza",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Veg Pizza",
    diet: "veg",
  },
  {
    id: "plain-cheese-pizza",
    name: "Plain Cheese Pizza",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Veg Pizza",
    diet: "veg",
  },
  {
    id: "five-topping-pizza",
    name: "Five Topping Pizza",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Veg Pizza",
    diet: "veg",
  },
  {
    id: "chilly-paneer-pizza",
    name: "Chilly Paneer Pizza",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Veg Pizza",
    diet: "veg",
  },
  {
    id: "cheese-corn-pizza",
    name: "Cheese Corn Pizza",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Veg Pizza",
    diet: "veg",
  },
  {
    id: "extra-toppings",
    name: "Extra Toppings",
    price: "₹100",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Veg Pizza",
    diet: "veg",
  },

  // ==========================================
  // SNACKS: NON-VEG PIZZA
  // ==========================================
  {
    id: "shah-junction-special-pizza-nonveg",
    name: "Shah Junction Special Pizza",
    price: "₹400",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Non-Veg Pizza",
    diet: "non-veg",
    isSpecial: true,
  },
  {
    id: "chilly-chicken-pizza",
    name: "Chilly Chicken Pizza",
    price: "₹400",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Non-Veg Pizza",
    diet: "non-veg",
  },
  {
    id: "onion-chicken-pizza",
    name: "Onion Chicken Pizza",
    price: "₹400",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Non-Veg Pizza",
    diet: "non-veg",
  },
  {
    id: "chicken-salami-cheese-pizza",
    name: "Chicken Salami Cheese Pizza",
    price: "₹400",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Non-Veg Pizza",
    diet: "non-veg",
  },
  {
    id: "chicken-corn-pizza",
    name: "Chicken Corn Pizza",
    price: "₹400",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Non-Veg Pizza",
    diet: "non-veg",
  },
  {
    id: "chicken-sausage-pizza",
    name: "Chicken Sausage Pizza",
    price: "₹400",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Non-Veg Pizza",
    diet: "non-veg",
  },
  {
    id: "chicken-capsicum-pizza",
    name: "Chicken Capsicum Pizza",
    price: "₹400",
    priceType: "single",
    primaryCategory: "Snacks",
    subcategory: "Non-Veg Pizza",
    diet: "non-veg",
  },

  // ==========================================
  // TANDOORI: FISH - SEASONAL
  // ==========================================
  {
    id: "fish-tikka",
    name: "Fish Tikka",
    price: "₹550",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Fish - Seasonal",
    diet: "non-veg",
  },
  {
    id: "fish-malai-tikka",
    name: "Fish Malai Tikka",
    price: "₹550",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Fish - Seasonal",
    diet: "non-veg",
  },
  {
    id: "fish-ajawani-tikka",
    name: "Fish Ajawani Tikka",
    price: "₹550",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Fish - Seasonal",
    diet: "non-veg",
  },
  {
    id: "grilled-fish-butter-lemon-sauce",
    name: "Grilled Fish Butter Lemon Sauce",
    price: "₹700",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Fish - Seasonal",
    diet: "non-veg",
  },
  {
    id: "fish-finger",
    name: "Fish Finger",
    price: "₹550",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Fish - Seasonal",
    diet: "non-veg",
  },
  {
    id: "fish-and-chips",
    name: "Fish & Chips",
    price: "₹550",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Fish - Seasonal",
    diet: "non-veg",
  },
  {
    id: "fish-masala",
    name: "Fish Masala",
    price: "₹550",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Fish - Seasonal",
    diet: "non-veg",
  },
  {
    id: "fish-tomato",
    name: "Fish Tomato",
    price: "₹550",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Fish - Seasonal",
    diet: "non-veg",
  },
  {
    id: "fish-curry",
    name: "Fish Curry",
    price: "₹550",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Fish - Seasonal",
    diet: "non-veg",
  },
  {
    id: "fish-amritsari",
    name: "Fish Amritsari",
    price: "₹550",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Fish - Seasonal",
    diet: "non-veg",
  },
  {
    id: "fish-pakoda",
    name: "Fish Pakoda",
    price: "₹550",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Fish - Seasonal",
    diet: "non-veg",
  },
  {
    id: "fish-chilly",
    name: "Fish Chilly",
    price: "₹550",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Fish - Seasonal",
    diet: "non-veg",
  },
  {
    id: "fish-lemon",
    name: "Fish Lemon",
    price: "₹550",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Fish - Seasonal",
    diet: "non-veg",
  },
  {
    id: "fish-garlic",
    name: "Fish Garlic",
    price: "₹550",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Fish - Seasonal",
    diet: "non-veg",
  },
  {
    id: "grilled-chicken-fish-sec",
    name: "Grilled Chicken",
    price: "₹600",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Fish - Seasonal",
    diet: "non-veg",
  },

  // ==========================================
  // TANDOORI: TANDOORI SNACKS - VEG
  // ==========================================
  {
    id: "paneer-tikka-tandoor",
    name: "Paneer Tikka",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Snacks - Veg",
    diet: "veg",
  },
  {
    id: "panner-achari-tikka",
    name: "Panner Achari Tikka",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Snacks - Veg",
    diet: "veg",
  },
  {
    id: "panner-haryali-tikke",
    name: "Panner Haryali Tikke",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Snacks - Veg",
    diet: "veg",
  },
  {
    id: "paneer-malai-tikka",
    name: "Paneer Malai Tikka",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Snacks - Veg",
    diet: "veg",
  },
  {
    id: "mushroom-tikka",
    name: "Mushroom Tikka",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Snacks - Veg",
    diet: "veg",
  },
  {
    id: "mushroom-malai-tikka",
    name: "Mushroom Malai Tikka",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Snacks - Veg",
    diet: "veg",
  },
  {
    id: "shubham-ki-moti",
    name: "Shubham Ki Moti",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Snacks - Veg",
    diet: "veg",
  },
  {
    id: "veg-seekh-kabab",
    name: "Veg. Seekh Kabab",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Snacks - Veg",
    diet: "veg",
  },
  {
    id: "tandoori-aloo",
    name: "Tandoori Aloo",
    price: "₹600",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Snacks - Veg",
    diet: "veg",
  },
  {
    id: "shahi-nawab-spl-veg-platter",
    name: "Shahi Nawab Spl. Veg. Platter",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Snacks - Veg",
    diet: "veg",
    isSpecial: true,
  },
  {
    id: "cheese-seekh-kabab",
    name: "Cheese Seekh Kabab",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Snacks - Veg",
    diet: "veg",
  },
  {
    id: "tandoori-paneer-hilton",
    name: "Tandoori Paneer Hilton",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Snacks - Veg",
    diet: "veg",
  },
  {
    id: "tandoori-stuffed-aloo",
    name: "Tandoori Stuffed Aloo",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Snacks - Veg",
    diet: "veg",
  },
  {
    id: "bharwa-mushroom",
    name: "Bharwa Mushroom",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Snacks - Veg",
    diet: "veg",
  },

  // ==========================================
  // TANDOORI: TANDOORI NON-VEG
  // ==========================================
  {
    id: "tandoori-chicken",
    name: "Tandoori Chicken",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-tikka-tandoor",
    name: "Chicken Tikka",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-malai-tikka-tandoor",
    name: "Chicken Malai Tikka",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-achari-tikka",
    name: "Chicken Achari Tikka",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-sonali-kabab",
    name: "Chicken Sonali Kabab",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-banzara",
    name: "Chicken Banzara",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-sekh-kabab",
    name: "Chicken Sekh Kabab",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-hariyali-tikka",
    name: "Chicken Hariyali Tikka",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "afgani-chicken",
    name: "Afgani Chicken",
    price: "₹450 / ₹700",
    priceHalf: "₹450",
    priceFull: "₹700",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "tangri-kabab",
    name: "Tangri Kabab",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "stuff-tangri-kabab",
    name: "Stuff Tangri Kabab",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-reshmi-kabab",
    name: "Chicken Reshmi Kabab",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "sahi-nawab-spl-non-veg-platter",
    name: "Sahi Nawab Spl. Non-Veg. Platter",
    price: "₹800",
    priceType: "single",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
    isSpecial: true,
  },
  {
    id: "chicken-chandani-kabab",
    name: "Chicken Chandani Kabab",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-rojari-kabab",
    name: "Chicken Rojari Kabab",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-dobara-kabab",
    name: "Chicken Dobara Kabab",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-asarpiya-kabab",
    name: "Chicken Asarpiya Kabab",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-jaipuri-kabab",
    name: "Chicken Jaipuri Kabab",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-jumta-kabab",
    name: "Chicken Jumta Kabab",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-thai-tikka",
    name: "Chicken Thai Tikka",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },
  {
    id: "lemon-chicken-tikka",
    name: "Lemon Chicken Tikka",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Tandoori",
    subcategory: "Tandoori Non-Veg",
    diet: "non-veg",
  },

  // ==========================================
  // CHINESE: CHINESE VEG. ORIENTAL
  // ==========================================
  {
    id: "veg-manchurian",
    name: "Veg. Manchurian Dry/Gravy",
    price: "₹200 / ₹240",
    priceType: "portion",
    priceHalf: "₹200",
    priceFull: "₹240",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "golden-fried-baby-corn",
    name: "Golden Fried Baby Corn",
    price: "₹240",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "mushroom-chilly",
    name: "Mushroom Chilly Dry/Gravy",
    price: "₹200 / ₹250",
    priceType: "portion",
    priceHalf: "₹200",
    priceFull: "₹250",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "cheese-chilly",
    name: "Cheese Chilly Dry/Gravy",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "honey-chilly-cauliflower",
    name: "Honey Chilly Cauliflower",
    price: "₹240",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "honey-chilly-potato",
    name: "Honey Chilly Potato",
    price: "₹220",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "crispy-veg-paper-salt",
    name: "Crispy Veg. Paper Salt",
    price: "₹230",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "crispy-veg-hot-sweet-sauce",
    name: "Crispy Veg. Hot & Sweet Sauce",
    price: "₹240",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "paneer-65",
    name: "Paneer 65",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "vegetable-hongkong",
    name: "Vegetable Hongkong",
    price: "₹280",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "baby-corn-salt-paper",
    name: "Baby Corn Salt Paper",
    price: "₹240",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "veg-choupsey",
    name: "Veg. Choupsey",
    price: "₹220",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "veg-bullet",
    name: "Veg. Bullet",
    price: "₹220",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "veg-noodles",
    name: "Veg. Noodles",
    price: "₹200",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "chicken-noodle",
    name: "Chicken Noodle",
    price: "₹250",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "non-veg",
  },
  {
    id: "cheese-noodle",
    name: "Cheese Noodle",
    price: "₹250",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "ginger-chilly-noodle",
    name: "Ginger Chilly Noodle",
    price: "₹240",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "veg-hakka-noodle",
    name: "Veg. Hakka Noodle",
    price: "₹240",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "chicken-hakka-noodle",
    name: "Chicken Hakka Noodle",
    price: "₹250",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "non-veg",
  },
  {
    id: "pan-fried-hakka-noodle-veg",
    name: "Pan Fried Hakka Noodle Veg.",
    price: "₹250",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "chilly-lemon-noodle",
    name: "Chilly Lemon Noodle",
    price: "₹230",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "chilly-garlic-noodle",
    name: "Chilly Garlic Noodle",
    price: "₹230",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "chicken-choupsey",
    name: "Chicken Choupsey",
    price: "₹260",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "non-veg",
  },
  {
    id: "american-choupsey",
    name: "American Choupsey",
    price: "₹280",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "veg-spring-roll",
    name: "Veg. Spring Roll",
    price: "₹220",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },
  {
    id: "chicken-spring-roll",
    name: "Chicken Spring Roll",
    price: "₹280",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "non-veg",
  },
  {
    id: "chinese-corn-roll",
    name: "Chinese Corn Roll",
    price: "₹250",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Veg. Oriental",
    diet: "veg",
  },

  // ==========================================
  // CHINESE: CHINESE NON-VEG
  // ==========================================
  {
    id: "chicken-in-pineapple-sauce",
    name: "Chicken in Pineapple Sauce",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Chinese",
    subcategory: "Chinese Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chill-chicken",
    name: "Chill Chicken",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Chinese",
    subcategory: "Chinese Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-hongkong",
    name: "Chicken Hongkong",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Chinese",
    subcategory: "Chinese Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-lollypop",
    name: "Chicken Lollypop",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Chinese",
    subcategory: "Chinese Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-manchurian",
    name: "Chicken Manchurian Dry/Gravy",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Chinese",
    subcategory: "Chinese Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-singapuri",
    name: "Chicken Singapuri",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Chinese",
    subcategory: "Chinese Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-sezwan-sauce",
    name: "Chicken Sezwan Sauce",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Chinese",
    subcategory: "Chinese Non-Veg",
    diet: "non-veg",
  },
  {
    id: "lemon-chicken-chinese",
    name: "Lemon Chicken",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Chinese",
    subcategory: "Chinese Non-Veg",
    diet: "non-veg",
  },
  {
    id: "ginger-chicken-chinese",
    name: "Ginger Chicken",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Chinese",
    subcategory: "Chinese Non-Veg",
    diet: "non-veg",
  },
  {
    id: "garlic-chicken-chinese",
    name: "Garlic Chicken",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Chinese",
    subcategory: "Chinese Non-Veg",
    diet: "non-veg",
  },

  // ==========================================
  // CHINESE: CHINESE RICE
  // ==========================================
  {
    id: "veg-fried-rice",
    name: "Veg. Fried Rice",
    price: "₹190",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Rice",
    diet: "veg",
  },
  {
    id: "chicken-fried-rice",
    name: "Chicken Fried Rice",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Rice",
    diet: "non-veg",
  },
  {
    id: "egg-fried-rice",
    name: "Egg Fried Rice",
    price: "₹230",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Rice",
    diet: "egg",
  },
  {
    id: "mix-fried-rice-non-veg",
    name: "Mix Fried Rice Non-Veg.",
    price: "₹240",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Rice",
    diet: "non-veg",
  },
  {
    id: "lemon-fried-rice",
    name: "Lemon Fried Rice",
    price: "₹240",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Rice",
    diet: "veg",
  },
  {
    id: "ginger-fried-rice",
    name: "Ginger Fried Rice",
    price: "₹240",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Rice",
    diet: "veg",
  },
  {
    id: "fried-rice-sezwan",
    name: "Fried Rice Sezwan",
    price: "₹240",
    priceType: "single",
    primaryCategory: "Chinese",
    subcategory: "Chinese Rice",
    diet: "veg",
  },

  // ==========================================
  // MAIN COURSE: INDIAN MAIN COURSE - VEG
  // ==========================================
  {
    id: "dal-makhni",
    name: "Dal Makhni",
    price: "₹200",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "dal-handi",
    name: "Dal Handi",
    price: "₹180",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "dal-amritsari",
    name: "Dal Amritsari",
    price: "₹180",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "dal-yellow",
    name: "Dal Yellow",
    price: "₹180",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "paneer-tikka-butter-masala",
    name: "Paneer Tikka Butter Masala",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "karahi-paneer",
    name: "Karahi Paneer",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "shahi-paneer",
    name: "Shahi Paneer",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "paneer-butter-masala",
    name: "Paneer Butter Masala",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "paneer-makhani-masala",
    name: "Paneer Makhani Masala",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "paneer-pasanda-masala",
    name: "Paneer Pasanda Masala",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "paneer-lababdar",
    name: "Paneer Lababdar",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "paneer-tikka-lababdar",
    name: "Paneer Tikka Lababdar",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "paneer-reshmi-masala",
    name: "Paneer Reshmi Masala",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "paneer-handi",
    name: "Paneer Handi",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "mutter-paneer",
    name: "Mutter Paneer",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "paneer-mumtaj-masala",
    name: "Paneer Mumtaj Masala",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "badami-baby-corn-paneer-masala",
    name: "Badami Baby Corn Paneer Masala",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "palak-paneer",
    name: "Palak Paneer",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "paneer-do-pyaza",
    name: "Paneer Do Pyaza",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "mushroom-do-pyaza",
    name: "Mushroom Do Pyaza",
    price: "₹280",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "mix-veg-main",
    name: "Mix Veg.",
    price: "₹280",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "chana-masala",
    name: "Chana Masala",
    price: "₹240",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "chana-pindi",
    name: "Chana Pindi",
    price: "₹240",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "veg-jal-fraze",
    name: "Veg. Jal Fraze",
    price: "₹240",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "corn-capsicum-masala",
    name: "Corn Capsicum Masala",
    price: "₹240",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "veg-jaypuri-korma",
    name: "Veg. Jaypuri Korma",
    price: "₹240",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "veg-navrattan-korma",
    name: "Veg. Navrattan Korma",
    price: "₹240",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "veg-makhani",
    name: "Veg. Makhani",
    price: "₹250",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "veg-kolhapuri",
    name: "Veg. Kolhapuri",
    price: "₹260",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "dum-aloo-kashmiri",
    name: "Dum Aloo Kashmiri",
    price: "₹260",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "dum-aloo",
    name: "Dum Aloo",
    price: "₹240",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "gobhi-masala",
    name: "Gobhi Masala",
    price: "₹250",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "mutter-malai-methi",
    name: "Mutter Malai Methi",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "paneer-methi-malai",
    name: "Paneer Methi Malai",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "mushroom-malai-methi",
    name: "Mushroom Malai Methi",
    price: "₹300",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "stuffed-tomato",
    name: "Stuffed Tomato",
    price: "₹280",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "malai-kofta",
    name: "Malai Kofta",
    price: "₹280",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },
  {
    id: "extra-veg-gravy",
    name: "Extra Veg. Gravy",
    price: "₹120",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Main Course - Veg",
    diet: "veg",
  },

  // ==========================================
  // MAIN COURSE: INDIAN CURRY - NON-VEG
  // ==========================================
  {
    id: "shahi-nawan-spl-chicken",
    name: "Shahi Nawan Spl. Chicken",
    price: "₹450 / ₹800",
    priceHalf: "₹450",
    priceFull: "₹800",
    priceType: "portion",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
    isSpecial: true,
  },
  {
    id: "butter-chicken",
    name: "Butter Chicken",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "karahi-chicken",
    name: "Karahi Chicken",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-handi",
    name: "Chicken Handi",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-tikka-lababdar",
    name: "Chicken Tikka Lababdar",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "tawa-chicken",
    name: "Tawa Chicken",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "cream-chicken",
    name: "Cream Chicken",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "rara-chicken",
    name: "Rara Chicken",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-lazzi",
    name: "Chicken Lazzi",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-sagwala",
    name: "Chicken Sagwala",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-masala",
    name: "Chicken Masala",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-curry",
    name: "Chicken Curry",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-dahi-wal",
    name: "Chicken Dahi Wal",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "chicken-achari",
    name: "Chicken Achari",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "methi-chicken",
    name: "Methi Chicken",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "punjabi-chicken",
    name: "Punjabi Chicken",
    price: "₹390 / ₹650",
    priceHalf: "₹390",
    priceFull: "₹650",
    priceType: "portion",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "mutton-rogan-josh",
    name: "Mutton Rogan Josh",
    price: "₹450",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "mutton-rara",
    name: "Mutton Rara",
    price: "₹450",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "mutton-curry",
    name: "Mutton Curry",
    price: "₹450",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "mutton-sagwala",
    name: "Mutton Sagwala",
    price: "₹450",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "mutton-masala",
    name: "Mutton Masala",
    price: "₹450",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "mutton-dahi-wala",
    name: "Mutton Dahi Wala",
    price: "₹450",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },
  {
    id: "extra-non-veg-gravy",
    name: "Extra Non-Veg. Gravy",
    price: "₹180",
    priceType: "single",
    primaryCategory: "Main Course",
    subcategory: "Indian Curry - Non-Veg",
    diet: "non-veg",
  },

  // ==========================================
  // RAITA
  // ==========================================
  {
    id: "plain-curd",
    name: "Plain Curd",
    price: "₹80",
    priceType: "single",
    primaryCategory: "Raita",
    subcategory: "Raita & Curd",
    diet: "veg",
  },
  {
    id: "aloo-raita",
    name: "Aloo Raita",
    price: "₹90",
    priceType: "single",
    primaryCategory: "Raita",
    subcategory: "Raita & Curd",
    diet: "veg",
  },
  {
    id: "boondi-raita",
    name: "Boondi Raita",
    price: "₹120",
    priceType: "single",
    primaryCategory: "Raita",
    subcategory: "Raita & Curd",
    diet: "veg",
  },
  {
    id: "mint-raita",
    name: "Mint Raita",
    price: "₹100",
    priceType: "single",
    primaryCategory: "Raita",
    subcategory: "Raita & Curd",
    diet: "veg",
  },
  {
    id: "mix-raita",
    name: "Mix Raita",
    price: "₹130",
    priceType: "single",
    primaryCategory: "Raita",
    subcategory: "Raita & Curd",
    diet: "veg",
  },
  {
    id: "pineapple-raita",
    name: "Pineapple Raita",
    price: "₹160",
    priceType: "single",
    primaryCategory: "Raita",
    subcategory: "Raita & Curd",
    diet: "veg",
  },
  {
    id: "fruit-raita",
    name: "Fruit Raita",
    price: "₹180",
    priceType: "single",
    primaryCategory: "Raita",
    subcategory: "Raita & Curd",
    diet: "veg",
  },
];
